### ISSUE TITLE
CKAN 2.x theme tweaks

### ISSUE THREAD

**Issue by johnmartin** [IATI/ckanext-iati#4]
## Todo
- [x] Organization on dataset page doesn't need `.context-info` border
- [x] Publisher listing doesn't fit across full width
- [x] No style for pagination links
- [x] `max-width: 100%` on `.context-info img`
- [x] `.active` state on organization read tabs not working
- [x] Organizations needs to be renamed to publishers throughout templates
- [x] Change favicon
- [ ] Change site title
- [x] `.input-prepend` needs to be imported from bootstrap 2.3
- [x] No icon for datasets on publisher_read
