### ISSUE TITLE
Review pending issues before production deployment

### ISSUE THREAD

**Issue by amercader** [IATI/ckanext-iati#41]
@stevieflow @Bjwebb I've pushed all these pending issues into the staging server. It would be great if you could have a look and make sure you are happy before I push into production.
- [x] #23 CSV description
- [ ] #27 Link to datastore - Waiting for PR
- [x] #29 Update API page
- [x] #30 Publisher listing page
- [x] #31 Publisher country search
- [x] #32 CSV upload animation
- [x] #33 New publisher field
- [x] #39 Remove linkedin and facebook icons
